# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rbSnpvec <- function(bedfn, bytes_snp, snp_vec, nindiv) {
    .Call('rbed_rbSnpvec', PACKAGE = 'rbed', bedfn, bytes_snp, snp_vec, nindiv)
}

rbSnpvecInd <- function(bedfn, bytes_snp, snp_vec, nindiv, indiv_vec) {
    .Call('rbed_rbSnpvecInd', PACKAGE = 'rbed', bedfn, bytes_snp, snp_vec, nindiv, indiv_vec)
}

rbSnpinter <- function(bedfn, bytes_snp, snp_start, snp_end, nindiv) {
    .Call('rbed_rbSnpinter', PACKAGE = 'rbed', bedfn, bytes_snp, snp_start, snp_end, nindiv)
}

rbSnpinterInd <- function(bedfn, bytes_snp, snp_start, snp_end, nindiv, indiv_vec) {
    .Call('rbed_rbSnpinterInd', PACKAGE = 'rbed', bedfn, bytes_snp, snp_start, snp_end, nindiv, indiv_vec)
}

readcols <- function(fn, colsel, nFirstSkipLines, nSkipUnit) {
    .Call('rbed_readcols', PACKAGE = 'rbed', fn, colsel, nFirstSkipLines, nSkipUnit)
}

